#!/usr/bin/env bash
# Install Nginx and Configure Nginx

sudo apt-get update
sudo apt-get install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
    }

    location /hello {
        return 200 "Hello World!";
    }
}" > /etc/nginx/sites-available/default
sudo nginx -t
