#!/usr/bin/env bash
# Install Nginx and Configure Nginx

sudo apt-get update
sudo apt-get install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
    }

    location /hello {
        return 200 "Hello World!";
    }
}" > /etc/nginx/sites-available/default
echo "server {
    listen 80;
    listen [::]:80;

    server_name _;

    location /redirect_me {
        return 301 http://www.example.com/;
    }
}" > /etc/nginx/sites-available/redirect_me
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/
sudo nginx -t
sudo service nginx restart
