#!/usr/bin/env bash
# This script configures Nginx to include a custom HTTP header in its HTTP response.
# The name of the custom HTTP header is X-Served-By, and the value is the hostname of the server Nginx is running on.

# Install Nginx
sudo apt-get update
sudo apt-get install nginx

# Configure Nginx
sudo rm /etc/nginx/sites-available/default
sudo echo "server {
	listen 80 default_server;
	listen[::]:80 default_server;
	root/var/www/html;
	index index.html index.htm;
	server_name 474988-web-02;
	location / {
		add_header X-Served-By '03-web-02'
		try_files $uri $uri/ -404;
	}
}"
# Restart Nginx
sudo systemctl reload nginx
