#!/usr/bin/env bash
# This script configures Nginx to include a custom HTTP header in its HTTP response. The name of the custom HTTP header is X-Served-By, and the value is the hostname of the server Nginx is running on.

# Install Nginx
sudo apt-get update -y && sudo apt-get upgrade -y
sudo apt-get -y install nginx

# Configure Nginx
sudo rm /etc/nginx/sites-available/default
sudo echo "server {
	listen 80 default_server;
	listen[::]:80 default_server;
	root/var/www/html;
	index index.html index.htm;
	server_name _;
	add_header X-Served-By 03-web-02;
	location / {
		try_files $uri $uri/ -404;
	}
}" > /etc/nginx/sites-available/default
# Restart Nginx
sudo nginx -t
sudo service restart nginx
