#!/usr/bin/env bash
# This script installs and configures HAProxy on your lb-01 server.

# Install HAProxy
sudo apt-get update -y && sudo apt-get upgrade -y
sudo apt-get -y install haproxy

# Configure HAProxy
sudo mkdir /etc/haproxy/certs/
sudo openssl dhparam -out /etc/haproxy/certs/dhparams.pem 2048
sudo cat /etc/letsencrypt/live/www.holberton.online/fullchain.pem /etc/letsencrypt/live/www.holberton.online/privkey.pem | sudo tee /etc/haproxy/certs/cert.pem > /dev/null
sudo echo "# Specify the DH parameter file
	ssl-dh-param-file /etc/haproxy/certs/dhparams.pemfrontend http

frontend www-https
	bind *:443 ssl crt /etc/haproxy/certs/cert.pem
	http-request redirect scheme https unless { ssl_fc }
	default_backend myservers

frontend http
	bind *:80
	mode http
	redirect scheme https code 301 if !{ ssl_fc }
	default_backend myservers

backend myservers
	mode http
	balance roundrobin
	server 474988-web-01 54.146.82.137:80 check
	server 474988-web-02 54.237.106.250:80 check
" >> /etc/haproxy/haproxy.cfg

# Manage HAProxy via an init script
sudo systemctl enable haproxy
sudo systemctl restart haproxy
