#!/usr/bin/env bash
# This script installs and configures HAProxy on your lb-01 server.

# Install HAProxy
sudo apt-get update -y && sudo apt-get upgrade -y
sudo apt-get -y install haproxy

# Configure HAProxy
sudo echo "frontend http
        bind *:80
        mode http
        default_backend myservers

backend myservers
        mode http
        balance roundrobin
        server 474988-web-01 54.146.82.137:80 check
        server 474988-web-02 54.237.106.250:80 check" >> /etc/haproxy/haproxy.cfg

# Manage HAProxy via an init script
sudo systemctl enable haproxy
sudo systemctl start haproxy
