#!/usr/bin/env bash
# Write a Bash script with the minimum number of commands to automate your fix.
sudo apt-get update
sudo apt-get install nginx
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
sudo systemctl reload nginx
