#!/usr/bin/env bash
# This script configures Nginx to listen on port 80
sudo apt-get -y install nginx
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
sudo service nginx stop
