#!/usr/bin/env bash
# Write a Bash script that creates the file /var/run/myscript.pid containing its PID
echo $$ > /var/run/myscript.pid
while true
do
        echo "To infinity and beyond"
        sleep 1
done
trap 'echo "I hate the kill command"; exit 0' SIGTERM
trap 'echo "Y U no love me?!"; exit 0' SIGINT
trap 'rm -f /var/run/myscript.pid; exit 0' SIGQUIT SIGTERM
