#!/usr/bin/env bash
# This displays a clock hours 0-12 and minutes 1-59.
hours=0
while [ $hours -le 12 ]
do
	minutes=1
	echo "Hour: $hours"
	while [ $minutes -le 59 ]
	do
		echo "$minutes"
		minutes=$((minutes+1))
	done
	hours=$((hours+1))
done
