#!/usr/bin/env bash
# Accesses a docker image to get access to the contents
docker run -p 8080:80 -d -it holbertonschool/265-0
docker ps
curl 0:8080
docker exec -ti 9d1d08282e20 /bin/bash
sudo apt-get update
sudo apt-get install apache2
sudo service apache2 start
echo 'ServerName localhost' >> /etc/apache2/apache2.conf
sudo apachectl configtest
