#!/usr/bin/env bash
# Takes a username as an argument and runs the whoami command under that user
if [ $# -ne 1 ]; then
    echo "Usage: $0 <username>"
    exit 1
fi
username="$1"
sudo -u "$username" whoami
