#!/usr/bin/env bash
# ensure that Nginx runs as the nginx user and listens on port 8080
# Configure Nginx to run as the nginx user
sudo sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf

# Listen on all active IPs on port 8080
sudo sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
