#!/bin/env bash
# Stop some workers gracefully
echo "Gracefully stopping some Gunicorn workers..."
kill -s TERM $(pgrep gunicorn)

# Wait for a few seconds to allow workers to finish processing requests
sleep 5

# Start new workers with updated code or configuration
echo "Starting new Gunicorn workers..."
gunicorn -b 0.0.0.0:5003 --workers 3 --access-logfile /tmp/airbnb-access.log --error-logfile /tmp/airbnb-error.log web_dynamic.2-hbnb:app

echo "Gunicorn reload complete!"
